[package]
name = "dodo-filetype"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
ignore = { workspace = true }
magika = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
confignet = { workspace = true }