[package]
name = "dodo-core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
ignore = { workspace = true }
magika = { workspace = true }
rayon = { workspace = true }
walkdir = "2.5.0"
