[package]
name = "dodo-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
dialoguer = "0.11.0"
dodo-core = { workspace = true }

[[bin]]
name = "dodo"
path = "src/main.rs"
